### ISSUE TITLE
No output on MacOS/Python 3.8

### ISSUE THREAD

**Issue by larsrinn** [P403n1x87/austin#43] opened 2020-05-14 12:01 UTC
### Description
When running `austin` on MacOS, it executes the code I want to run but it doesn't yield any output that can be passed along to `flamegraph`. Also trying to start `austin-tui` and `austin-web` gives errors *"Took too long to start."*, no matter the value I set for `timeout` (it doesn't even wait untill the time has passed to raise that error)

### Steps to Reproduce

1. Install `austin` on MacOS (Catalina, 10.15.4) and using python 3.8 following the instructions from the Readme (using autotools)
2. Run `austin python test.py | echo` -> no output, hence there is nothing to pass along to flamegraph
3. Run `austin-tui --timeout=10000 python test.py`

**Expected behavior:** 
For 2: Yield output to pass along to flamegraph
For 3: Show the results in tui

**Actual behavior:** 
For 2: Nothing, but script runs as expected
For 3: TUI opens for a short period, then closes and shows error it took to long to start

**Reproduces how often:** 
Always

### Versions

* MacOS 10.15.4
* Python 3.8
* Austin 1.0.0

**Comment by RhetTbull** [comment] 2020-05-14 14:15
I'm experiencing the same thing:

```sh
[I] ➜ python --version
Python 3.8.2
[I] ➜ python -c "import platform; print(platform.mac_ver())"
('10.15.4', ('', '', ''), 'x86_64')
[I] ➜ austin --version
austin 1.0.0
[I] ➜ austin -o a.out ./test.py
[I] ➜ lsa -lah a.out
-rw-r--r--@ 1 rhet  staff     0B May 14 07:09 a.out
```

### Versions

- MacOS 10.15.4
- Python 3.8.2 (Anaconda)
- Austin 1.0.0

austin built from sources via:
```sh
git clone --depth=1 https://github.com/P403n1x87/austin.git
cd austin
gcc -O3 -Wall src/*.c -o src/austin
```

**Comment by P403n1x87** [comment] 2020-05-14 14:44
Thanks for reporting this issue. I just realised that the README lacks some important information about Austin on MacOS. There is a good chance that this issue is being caused by System Integrity Protection. If the Python executable you are using resides in /usr/bin, then even `sudo` won't help here, unless SIP is disabled. In order to avoid disabling SIP, the Python executable should live outside of /usr/bin (but the use of `sudo` is still required). Hence, if the executable is in /usr/bin, may I ask you to run Austin from, e.g. within a virtual environment please (with `sudo`)?

**Comment by RhetTbull** [comment] 2020-05-14 14:56
I tried within a virtual env and using sudo, still same result.  I am running in iTerm2 which already is set to "Full Disk Access" and "Developer Tools" in Settings | Security & Privacy. 

```sh
[I] ➜ which python
/Users/rhet/opt/anaconda3/envs/osxphotos/bin/python
[I] ➜ sudo austin -o t.out ./test.py
[I] ➜ ls -lah t.out
-rw-r--r--@ 1 rhet  staff     0B May 14 07:51 t.out
```

**Comment by larsrinn** [comment] 2020-05-14 14:58
Sure, `austin python test.py | echo` still doesn't yield any output

`austin-tui python test.py` doesn't crash but still doesn't show any output:
![grafik](https://user-images.githubusercontent.com/22575361/81949762-7b8b0c80-9603-11ea-8309-ebf4a415f96e.png)

Looking at the `CMD` output, it doesn't seem to use the python version I passed in when calling `austin`:
![grafik](https://user-images.githubusercontent.com/22575361/81950187-ed635600-9603-11ea-9eff-37bc080dc06d.png)

The same is true, if I call the executable explicitly: ` sudo austin-tui ./.venv/bin/python test.py`

**Comment by P403n1x87** [comment] 2020-05-14 15:00
Thanks for the feedback. I will look into this as soon as I can.

**Comment by P403n1x87** [comment] 2020-05-16 16:41
Hi there.

I have prepared a PR with a fix for this issue. May I ask you to try checking out the branch `hotfix/3.8-support` and check that Austin now works as expected, please?

Thanks.

**Comment by RhetTbull** [comment] 2020-05-19 05:01
I tried the hotfix on MacOS 10.15.4 but unfortunately still get the same results.
`sudo austin /path/to/python t.py | echo` yields no output 
`sudo austin -o t.out /path/to/python t.py` runs but yields empty output file 
and 
`sudo austin-tui /path/to/python t.py` runs but yields no output exactly as @larsrinn reported earlier in this thread

Tried both anaconda python 3.7 and 3.8

**Comment by P403n1x87** [comment] 2020-05-19 20:13
@RhetTbull Thanks for the further feedback. I should have fixed the problem now. I have tested with Anaconda (Python 3.7 and 3.8) and Python 3.8 from Homebrew and all seems to work as expected now. I would really appreciate if you could pull the latest commit from `hotfix/3.8-support` and test again.

Cheers!

**Comment by RhetTbull** [comment] 2020-05-20 03:52
@P403n1x87 Success!  `hotfix/3.8-support` seems to work. I tried both the `austin` and `austin-tui` and both worked.  One note: I did need to run with `sudo` so perhaps worth a mention in the docs.  Thanks for the quick fix!

**Comment by P403n1x87** [comment] 2020-05-20 07:02
Excellent! Thanks for testing and sharing the results. I have added a note in the resend about SIP on macOS.

**Closed** 2020-05-20 13:02 UTC
Labels: bug
